[package]
name = "rustable"
description = "Another crate for using Bluetooth Low Energy with Bluez."
version = "0.1.1"
authors = ["Curtis Maves <curtismaves@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/cmaves/rustable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rustbus = { git = "https://github.com/KillingSpark/rustbus.git" }
rustbus = "0.6.0"
nix = "0.17.0"
