[package]
name = "rustable"
version = "0.1.0"
authors = ["Curtis Maves <curtismaves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbus = { git = "https://github.com/KillingSpark/rustbus.git" }
nix = "0.17.0"
